#PBS -N Arm_CNT.140.140.146.146.analysis
#PBS -l nodes=1:ppn=8,walltime=2400:00:00
#PBS -l mem=10000mb
#PBS -q cores-16
#--------------------------------
echo "Node Name: $HOSTNAME"
setenv SCRDIR /scratch/$LOGNAME/$PBS_JOBID/
/bin/mkdir -p $SCRDIR
cd $SCRDIR
cp $PBS_O_WORKDIR/BN.x $SCRDIR
cp $PBS_O_WORKDIR/CH.airebo $SCRDIR
cp $PBS_O_WORKDIR/run.par $SCRDIR
cp $PBS_O_WORKDIR/Coords.xyz $SCRDIR
./BN.x
cp -f $SCRDIR/* $PBS_O_WORKDIR
rm -rf $SCRDIR
